language: groovy
jdk:
    - oraclejdk7
    - openjdk7
before_install: git checkout $(git branch --contains $(git rev-parse HEAD)|tail -n1|tr -d ' ')
after_success: ./gradlew bintrayUpload
branches:
    only:
        - master
